// File generated by FlutterFire CLI & Parkiko Integration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'AIzaSyParkikoDemoKeyWeb000123456789',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WEB_APP_ID',
      defaultValue: '1:109283746501:web:9c8d7e6f5a4b3c2d1e0f',
    ),
    messagingSenderId: '109283746501',
    projectId: 'parkiko-valet',
    authDomain: 'parkiko-valet.firebaseapp.com',
    storageBucket: 'parkiko-valet.firebasestorage.app',
    measurementId: 'G-PARKIKO1234',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_API_KEY',
      defaultValue: 'AIzaSyParkikoDemoKeyAndroid12345678',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_ANDROID_APP_ID',
      defaultValue: '1:109283746501:android:3b4c5d6e7f8a9b0c',
    ),
    messagingSenderId: '109283746501',
    projectId: 'parkiko-valet',
    storageBucket: 'parkiko-valet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'AIzaSyParkikoDemoKeyIos1234567890abc',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_IOS_APP_ID',
      defaultValue: '1:109283746501:ios:2a3b4c5d6e7f8a9b0c1d',
    ),
    messagingSenderId: '109283746501',
    projectId: 'parkiko-valet',
    storageBucket: 'parkiko-valet.firebasestorage.app',
    iosBundleId: 'com.parkiko.parkiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_MACOS_API_KEY',
      defaultValue: 'AIzaSyParkikoDemoKeyMac1234567890abc',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_MACOS_APP_ID',
      defaultValue: '1:109283746501:ios:2a3b4c5d6e7f8a9b0c1d',
    ),
    messagingSenderId: '109283746501',
    projectId: 'parkiko-valet',
    storageBucket: 'parkiko-valet.firebasestorage.app',
    iosBundleId: 'com.parkiko.parkiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WINDOWS_API_KEY',
      defaultValue: 'AIzaSyParkikoDemoKeyWin1234567890abc',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WINDOWS_APP_ID',
      defaultValue: '1:109283746501:web:win9c8d7e6f5a4b3c2d',
    ),
    messagingSenderId: '109283746501',
    projectId: 'parkiko-valet',
    authDomain: 'parkiko-valet.firebaseapp.com',
    storageBucket: 'parkiko-valet.firebasestorage.app',
  );
}
