// File generated by FlutterFire CLI & Parkiko Integration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps on project parkiko-cd383.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'AIzaSyCDGZwcHeiUPyLHu1YjrTWW6ncvuhYtnW8',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WEB_APP_ID',
      defaultValue: '1:773603884657:web:6dd81fd716c705311e65d0',
    ),
    messagingSenderId: '773603884657',
    projectId: 'parkiko-cd383',
    authDomain: 'parkiko-cd383.firebaseapp.com',
    storageBucket: 'parkiko-cd383.firebasestorage.app',
    measurementId: 'G-5C212WVZWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_API_KEY',
      defaultValue: 'AIzaSyDk4AEdNjpO6ANjyRyOAF9DvGEndWQX-IE',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_ANDROID_APP_ID',
      defaultValue: '1:773603884657:android:fbf12c506f83bdfb1e65d0',
    ),
    messagingSenderId: '773603884657',
    projectId: 'parkiko-cd383',
    storageBucket: 'parkiko-cd383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'AIzaSyBo8Ez37DHVeSnqCrMmAYn-9qlMSJ3e-TM',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_IOS_APP_ID',
      defaultValue: '1:773603884657:ios:8648cfdfa549240c1e65d0',
    ),
    messagingSenderId: '773603884657',
    projectId: 'parkiko-cd383',
    storageBucket: 'parkiko-cd383.firebasestorage.app',
    iosBundleId: 'com.parkiko.parkiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_MACOS_API_KEY',
      defaultValue: 'AIzaSyBo8Ez37DHVeSnqCrMmAYn-9qlMSJ3e-TM',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_MACOS_APP_ID',
      defaultValue: '1:773603884657:ios:8648cfdfa549240c1e65d0',
    ),
    messagingSenderId: '773603884657',
    projectId: 'parkiko-cd383',
    storageBucket: 'parkiko-cd383.firebasestorage.app',
    iosBundleId: 'com.parkiko.parkiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WINDOWS_API_KEY',
      defaultValue: 'AIzaSyCDGZwcHeiUPyLHu1YjrTWW6ncvuhYtnW8',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WINDOWS_APP_ID',
      defaultValue: '1:773603884657:web:6dd81fd716c705311e65d0',
    ),
    messagingSenderId: '773603884657',
    projectId: 'parkiko-cd383',
    authDomain: 'parkiko-cd383.firebaseapp.com',
    storageBucket: 'parkiko-cd383.firebasestorage.app',
  );
}
